### ISSUE TITLE
Trawl through all meta data to make category data files

### ISSUE THREAD

**Issue by briandfoy** [tpf/perldotcom#82]
To make a "related articles" widget we need a way to preprocess that stuff. Instead of struggling to do this in Hugo, do it as batch processing.

- [x] Extract the metadata from each file (a nice library to do would make it easier for other tools)
- [x] Extract the category, keywords, and tags for each article
- [x] Make one file per category with a list of articles. The filename is like category.json, tag.json, and so on
- [x] Now an article can grab that file and pick K articles from it
- [x] These json files are publicly available so external tools can grab them

**Comment by dnmfarrell** [comment]
As you point out, this would be very helpful for #72.

I'm sure we could use this data for other interesting widgets / analytics on the site too

**Comment by sdeseille** [comment]
Hello, i would like to try working on that issue. 
It's hacktoberfest and i will be happy to do that for the Perl community.
Regards

**Comment by briandfoy** [comment]
@sdeseille Go for it. Ask if you need help.

And, I recommend working in a topic branch:

    git checkout -b sdeseille/categories

**Comment by sdeseille** [comment]
hi Brian
Thanks, i just forked and created a branch.
I would like to know where in project directory tree i could put the libs dedicated to the batch processing.
regards

**Comment by sdeseille** [comment]
hello I planed to name the lib "Pdc::Opendata".
Does it make sense for you ? Are you agree ?

Regards

**Comment by briandfoy** [comment]
I don't know what you have planned, but I don't think I would have made a module. What are you thinking about doing?

**Comment by sdeseille** [comment]
I was thinking to gather all function in one module. I will push on my
branch the first work this morning. You will see what i planed to do.
Regards

Le ven. 5 oct. 2018 à 01:40, brian d foy <notifications@github.com> a
écrit :

**Comment by sdeseille** [comment]
hello

I pushed my first work on /sdeseille/categories branch.
When you say to use Local Namespace you mean replace "Pdc::Opendata" just by "Local" ?

regards

**Comment by sdeseille** [comment]
hi @briandfoy 

Can you take a look on what i have done.
I will be happy to received your advice.

regards

**Comment by briandfoy** [comment]
I would have just made a standalone script to do the task. Having a method to extract the metadata is interesting.

What are you stuck on?

**Comment by sdeseille** [comment]
@briandfoy 
In fact I understood you would like a module when i read that comment "(a nice library to do would make it easier for other tools)". But well it is note mandatory. I can put all the code in a standalone script named per example "metadata_toolbox.pl". What do you think about that ?

**Comment by briandfoy** [comment]
Solve the problem anyway that you like. The first step is to get the problem solved. From there we can rearrange the particular solution. If you need much more direction I think it might be easier if you find a different issue to work on and I'll handle this one myself.

**Comment by sdeseille** [comment]
Ok thank. I keep that issue. I'm not far to solve it.

Regards
sdeseille

Le lun. 8 oct. 2018 à 23:56, brian d foy <notifications@github.com> a
écrit :

**Comment by sdeseille** [comment]
Hi @briandfoy 

Please review my PR.
I plan to work on others features next you end the review.

many thanks

**Comment by briandfoy** [comment]
The `Local::Metadata` module and the _bin/collate_metadata_ program does the work. It creates a bunch of files in _collations_ for now. There's still work to do on it though.

**Comment by briandfoy** [comment]
I've created JSON files for all this and they are now part of the site under /json/
